<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Bixie\\PkFramework\\' => array($vendorDir . '/bixie/pk-framework/src'),
);
